In [ ]:
#remember about clearing cache after changes in other files

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

##if not working, try 'activate tensorflow' in console/terminal
print(tf.__version__)

2.4.1


In [12]:
#load images as arrays
from filesService import getNumbers
labels, images = getNumbers()
print(images)
print('labels and images loaded to memory')


[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 254 255 255]
  [255 254 255 255]
  [255 253 255 255]]

 [[254 254 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 253 255 255]
  [253 251 254 255]
  [255 253 255 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [255 255 255 255]
  ...
  [255 253 255 255]
  [253 251 254 255]
  [251 249 251 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [254 253 255 255]
  [255 254 255 255]
  [252 250 253 255]]

 [[251 250 251 255]
  [251 250 250 255]
  [251 252 249 255]
  ...
  [253 253 252 255]
  [249 249 249 255]
  [251 251 250 255]]

 [[151 149 163 255]
  [160 158 172 255]
  [168 166 181 255]
  ...
  [250 247 255 255]
  [241 238 246 255]
  [255 253 255 255]]]
labels and images loaded to memory


In [15]:
print(type(labels))
print(type(images))

<class 'numpy.str_'>
<class 'numpy.ndarray'>
